### ISSUE TITLE
Invalid license in library.properties

### ISSUE THREAD

**Issue by njh** [ldab/lis3dh-motion-detection#2]
Hi,

I maintain https://www.arduinolibraries.info and noticed that you have an invalid `license=GNU` line in [library.properties](https://github.com/ldab/lis3dh-motion-detection/blob/master/library.properties).

It should be a value from the SPDX License List: https://spdx.org/licenses/

I suspect you mean one of these two:
* `GPL-3.0-only`
* `GPL-3.0-or-later`

Would you like me to help by submitting a Pull Request?

nick.

**Comment by ldab** [comment]
Thanks, fixed 8c949eb416a48613d41834025a95aef61017fd15

**Comment by njh** [comment]
Wow, speedy!
